version: "3.8"
services:
  frontend_fv:
    image: "formulario_frontend"
    container_name: "FORMULARIO_FRONTEND"
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - "./:/app"
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - TZ=America/Lima
    # command: npm run build
    command: /bin/sh -c "npm install && npm run build"
    networks:
      - dev-network

networks:
  dev-network:
    name: dev-network
    driver: bridge

